train_data_path: ./tsp50_test_concorde.txt
val_data_path: ./tsp50_test_concorde.txt
node_size: 50
train_batch_size: 80 # [tsp50, tsp100, tsp500, tsp1000]: 80
val_batch_size: 1280 # [tsp50, tsp100]: 1280, [tsp500, tsp1000]: 128
test_batch_size: 1280
G: 1 # the number of multistart nodes
resume_checkpoint: ./TSP50-epoch=03-opt_gap=83.0995.ckpt
gpus: [0, 1, 2, 3]
max_epochs: 100
enc_num_layers: 6
dec_num_layers: 6
d_model: 128
d_ff: 512
h: 8
dropout: 0.1
smoothing: 0.1
seed: 1
lr: 0.5
betas: [0.9, 0.98]
eps: 1e-9
factor: 1.0
warmup: 400
encoder_pe: 2D # None, 2D
decoder_pe: circular PE # None, 1D, circular 
decoder_lut: memory # shared, unshared, memory
comparison_matrix: memory # encoder_lut, decoder_lut, memory