train_data_path: ./tsp100_train_concorde.txt
val_data_path: ./tsp100_test_concorde.txt
node_size: 100
train_batch_size: 80 # [tsp50, tsp100, tsp500, tsp1000]: 80, [tsp10000]: 8
val_batch_size: 1280 # [tsp50, tsp100, tsp500, tsp1000]: 1280, [tsp10000]: 16
test_batch_size: 1280
G: 1
resume_checkpoint: None
gpus: [0, 1, 2, 3]
max_epochs: 1
enc_num_layers: 24
dec_num_layers: 24
d_model: 512
d_ff: 2048
h: 8
dropout: 0.1
smoothing: 0.1
seed: 1
lr: 0.5
betas: [0.9, 0.98]
eps: 1e-9
factor: 1.0
warmup: 400
encoder_pe: 2D # None, 2D
decoder_pe: circular # None, 1D, circular 
decoder_lut: memory # shared, unshared, memory
comparison_matrix: memory # encoder_lut, decoder_lut, memory